import Navbar from "@/component/shared/Navbar";
import "./globals.css";

import { Roboto } from 'next/font/google'
 
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})
 

export const metadata = {
  title: "Abc website",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={roboto.className} data-theme="light">
      <body >
        <Navbar></Navbar>
        {children}
        </body>
    </html>
  );
}
